version: '3.7'
volumes: 
  db:
  data:

services:
  mariadb:
    container_name: pteropanel_db
    env_file: ./static/.env
    image: mariadb:latest
    restart: always
    volumes:
    - db:/var/lib/mysql
  redis:
    container_name: pteropanel_redis
    image: redis:alpine
    restart: always
  panel:
    container_name: pteropanel
    depends_on:
    - redis
    - mariadb
    env_file: ./static/.env
    image: ccarney16/pterodactyl-panel:latest
    restart: always
    volumes:
    - data:/data
    ports:
    - 43738:80
  