---

- name: Install containerd
  hosts: kube_master:kube_worker
  pre_tasks:
    - name: Check if containerd is already installed
      stat:
        path: /lib/systemd/system/containerd.service
      register: containerd_service
  roles:
    - role: geerlingguy.containerd
      when: not containerd_service.stat.exists
  post_tasks:
    - name: Configure system for containerd
      block:
        - name: Set net.bridge.bridge-nf-call-iptables to 1
          lineinfile:
            path: /etc/sysctl.conf
            line: net.bridge.bridge-nf-call-iptables = 1
        - name: Enable IP forwarding
          shell: echo '1' > /proc/sys/net/ipv4/ip_forward
        - name: Reload sysctl configuration
          shell: sysctl --system
        - name: Load overlay and br_netfilter modules
          shell: |
            modprobe overlay
            modprobe br_netfilter
      when: not containerd_service.stat.exists

- name: Install Kubernetes
  hosts: kube_master:kube_worker
  tasks:
    - name: Check for Kubernetes
      shell: command -v kubectl >/dev/null 2>&1
      register: kubectl_binary
      ignore_errors: yes
    - name: Install Kubernetes
      block:
        - name: Disable swap
          shell: |
            swapoff -a 
            sed -i '/swap/d' /etc/fstab
        - name: Install prerequisites
          apt:
            pkg:
            - apt-transport-https
            - ca-certificates
            - curl
        - name: Download GCP public signing key
          shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        - name: Add Kubernetes repository
          shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        - name: Install Kubernetes
          apt:
            name: ['kubelet', 'kubeadm', 'kubectl']
            update_cache: true
            state: present # holds automatically
      when: kubectl_binary.rc == 127

- name: Run Kubernetes cluster commands
  hosts: kube_master:kube_worker
  pre_tasks:
    - name: Verify that mandatory variables are defined
      assert:
        that: endpoint is defined
        fail_msg: "Required variable endpoint is missing!"
        success_msg: "Required variable endpoint is present"
    - name: Check if cluster already intiated
      stat:
        path:  /etc/kubernetes/manifests/kube-apiserver.yaml
      register: apiserver_manifest
  tasks:
    - name: Cluster creation
      block:
        - name: Initialize cluster
          shell: "kubeadm init --pod-network-cidr={{ cidr|default('192.168.0.0/16') }} --control-plane-endpoint={{ endpoint }}" # TODO: turn these into variables
          register: init_cmd
        - name: Check initialization status
          fail:
            msg: Non-zero return code for kubeadm init. Cluster initialization failed?
          when: not (init_cmd.rc == 0)
        - name: Copy configs
          shell: |
            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
        - name: Install Calico pod network
          shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when:
        - "'kube_master' in group_names"
        - not apiserver_manifest.stat.exists
    - name: Create join token
      shell: "kubeadm token create --description 'Temporary join token (Ansible)' --ttl 1h --print-join-command"
      register: token_create
      when: "'kube_master' in group_names"
    - name: Join cluster
      shell: "{{  token_create.stdout.strip() }}"
      when: "'kube_worker' in group_names"
    - name: Delete join token
      shell: "kubeadm token delete {{ token_create.stdout.strip().split('--token ')[1].split(' ')[0] }}"
      when: "'kube_master' in group_names"