- name: Install NFS Server
  hosts: nfs_server
  pre_tasks:
    - name: Verify that mandatory variables are defined
      assert:
        that: exports is defined
        fail_msg: "Required variable exports is missing!"
        success_msg: "Required variable exports is present"
    - name: Ensure share directory exists
      file:
        path: "{{ item.split()[0] }}"
        state: directory
        recurse: true
      loop: "{{ exports }}"
  roles:
    - role: geerlingguy.nfs
      nfs_exports: "{{ exports }}"
  
- name: Install NFS Client
  hosts: nfs_client
  tasks:
    - name: Ensure nfs-common is installed
      apt:
        name: nfs-common