version: '3.7'
volumes: 
  db:
  ptero:

services:
  mariadb:
    container_name: pteropanel_db
    env_file: .env
    image: linuxserver/mariadb
    restart: always
    volumes:
    - db:/config
  redis:
    container_name: pteropanel_redis
    image: redis:alpine
    restart: always
  panel:
    container_name: pteropanel
    depends_on:
    - redis  
    - mariadb
    env_file: .env
    image: ccarney16/pterodactyl-panel:latest
    restart: always
    volumes:
    - ptero:/data
    ports:    
    - 43738:80

  