- name: Ensure wheel group exists
  group:
    name: wheel
    state: present

- name: Disable usage of su for non-wheel users
  lineinfile:
      path: /etc/pam.d/su
      line: auth       required   pam_wheel.so