- name: Install Docker
  command: curl -sSL https://get.docker.com/ | CHANNEL=stable bash
  become: true

- name: Install Compose
  command: curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
  become: true

- name: Make Compose executable
  command: chmod +x /usr/local/bin/docker-compose
  become: true

- name: Change Docker data root
  copy:
    dest: /etc/systemd/system/docker.service.d/data-root.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd --data-root /srv/docker/ -H fd://

- name: Enable and start the Docker service
  service:
    name: docker
    state: started
    enabled: true
  become: true

