version: '3.7'
volumes: 
  bitwarden:

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: always
    container_name: bitwarden
    ports:
      - '80:80'
    healthcheck:
      test: ['CMD', 'wget --quiet --tries=1 --spider', 'http://localhost:80']
      interval: 30s
      timeout: 5s
    volumes:
      - bitwarden:/data/

