version: '3.7'
volumes: 
  data:

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: always
    container_name: bitwarden
    ports:
      - 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
    volumes:
      - data:/data/

