version: '3.7'

volumes:
  conf:
  data:
  extensions:
  psql-data:

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    expose:
      - 9000
    ports:
      - '1055:9000'
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - conf:/opt/sonarqube/conf
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
  db:
    image: postgres
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - psql-data:/var/lib/postgresql/data
