version: '3.7'

services:
  mariadb:
    container_name: pteropanel_db
    env_file: .env
    image: mariadb:latest
    restart: always
    volumes:
    - ./data/db:/var/lib/mysql
  redis:
    container_name: pteropanel_redis
    image: redis:alpine
    restart: always
  panel:
    container_name: pteropanel
    depends_on:
    - redis
    - mariadb
    env_file: .env
    image: ccarney16/pterodactyl-panel:latest
    restart: always
    volumes:
    - ./data/ptero:/data
    ports:
    - 43738:80
  