version: '3.7'

services:
  seafile:
    image: gronis/seafile
    container_name: seafile
    restart: always
    volumes:
      - /mnt/seafile:/seafile
    ports:
      - 41729:8000
      - 41730:8082
    environment:
      - SEAFILE_NAME=Seafile
      - SEAFILE_ADDRESS=file.weilbyte.net
      - SEAFILE_ADMIN=seafile@example.com
      - SEAFILE_ADMIN_PW=seafile
