- name: Basic playbook to ready Ubuntu 20.04 for provisioning
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Update all packages
      package:
        name: '*'
        state: latest
      become: true

    - name: Remove snap
      apt:
        name: snapd
        purge: true
        state: absent
      become: true

    - name: Lower SSH Authentication attempts
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#MaxAuthTries 6'
        replace: 'MaxAuthTries 1'
      become: true

    - name: Disable password authentication
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        replace: 'PasswordAuthentication no'
      become: true

    - name: Disable root login
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin prohibit-password'
        replace: 'PermitRootLogin no'
      become: true

    - name: Restrict su to wheel
      replace:
        path: /etc/pam.d/su
        regexp: '# auth       required   pam_wheel.so'
        replace: 'auth       required   pam_wheel.so group=wheel '
      become: true

    - name: Enable password-less sudo for wheel
      lineinfile:
        path: /etc/sudoers
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      become: true

    - name: Ensure wheel exists
      group:
        name: wheel
        state: present
      become: true

    - name: Add Ansible user
      user:
        name: ansible
        comment: Ansible user
        shell: /bin/bash
        group: wheel
      become: true

    - name: Add Ansible key to user
      authorized_key:
        user: ansible
        state: present
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiAQf0GuePZ9k7SMlUukweW76jHURCf26mY7xpuhnBd Ansible"
      become: true

    - name: Remove autoinstall and hostname files
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/cloud/cloud.cfg.d/99-installer.cfg
        - /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
        - /etc/netplan/00-installer-config.yaml
        - /etc/hostname
        - /etc/hosts
      become: true

    - name: Download lvm extend script
      get_url:
        url: https://gist.githubusercontent.com/Weilbyte/c264049ba5943d5b08ba9595a860af81/raw/107a9ece1affd426b95de3e3932cb63546246501/extend.sh
        dest: /usr/local/bin/autoextend
        mode: a+x
      become: true

    - name: Create lvm extend cronjob
      cron:
        name: autoextend
        job: /usr/local/bin/autoextend
        user: root
        state: present
      become: true

    - name: Run cloud-init clean
      shell: cloud-init clean -l -s
      become: true

    - name: Ensure per-instance directory exists
      file: path=/var/lib/cloud/scripts/per-instance state=directory
      become: true

    - name: Add per-instance reboot script
      copy:
        dest: /var/lib/cloud/scripts/per-instance/reboot
        content: |
          #!/bin/bash
          shutdown -r now
        mode: a+x
      become: true

    - name: Restart SSH service
      service: 
        name: sshd
        state: restarted
      become: true

    - name: Disable ubuntu account
      user: 
        name: ubuntu
        password: '!'
      become: true