version: '3.7'
volumes: 
  data:

services:
  guacamole:
    container_name: guacamole
    image: oznu/guacamole:latest
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
    volumes:
    - data:/config
    ports:
    - 43740:8080
    environment: 
    - EXTENSIONS=auth-totp

  