version: '3.7'
volumes: 
  taiga-media:
services:
  database:
    image: postgres:12
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: <-- secret -->
  taiga:
    image: devinsolutions/taiga:latest
    restart: always
    container_name: taiga
    ports:
      - 8080
    command:
      - migrate
      - run-server
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/v1"]
      interval: 30s
      timeout: 5s
    stop_signal: SIGHUP
    volumes:
      - taiga-media:/srv/taiga-back/media
      - ./static/front.json:/etc/opt/taiga-front/conf.json:ro
      - ./static/back.py:/etc/opt/taiga-back/settings/settings.py:ro 


    